# Generated by Django 5.2 on 2025-05-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
            ],
            options={
                "verbose_name": "Advantage",
                "verbose_name_plural": "Advantages",
            },
        ),
        migrations.CreateModel(
            name="ChoiceName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice_name",
                    models.CharField(max_length=255, verbose_name="Choice name"),
                ),
            ],
            options={
                "verbose_name": "Choice name",
                "verbose_name_plural": "Choice names",
            },
        ),
        migrations.CreateModel(
            name="Disadvantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
            ],
            options={
                "verbose_name": "Disadvantage",
                "verbose_name_plural": "Disadvantages",
            },
        ),
        migrations.CreateModel(
            name="Localization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "localization_name",
                    models.CharField(max_length=255, verbose_name="Localization name"),
                ),
            ],
            options={
                "verbose_name": "Localization",
                "verbose_name_plural": "Localizations",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=255, verbose_name="Tag name")),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice", models.CharField(max_length=255, verbose_name="Choice")),
                ("order", models.IntegerField(verbose_name="Order")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "choice_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.choicename",
                        verbose_name="Choice name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Choice",
                "verbose_name_plural": "Choices",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(max_length=255, verbose_name="Group name"),
                ),
                (
                    "localization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.localization",
                        verbose_name="Localization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
                "unique_together": {("localization", "group_name")},
            },
        ),
        migrations.CreateModel(
            name="SubGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subgroup_name",
                    models.CharField(max_length=255, verbose_name="Subgroup name"),
                ),
                ("code", models.CharField(max_length=50, verbose_name="Code")),
                ("abstract", models.TextField(verbose_name="Abstract")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "mix_localization",
                    models.BooleanField(default=False, verbose_name="Mix localization"),
                ),
                ("env", models.TextField(verbose_name="Environment")),
                (
                    "env_secondary",
                    models.TextField(verbose_name="Secondary environment"),
                ),
                ("env_desc", models.TextField(verbose_name="Environment description")),
                ("potential", models.TextField(verbose_name="Potential")),
                ("size", models.CharField(max_length=50, verbose_name="Size")),
                (
                    "difficulty_of_implementation",
                    models.TextField(verbose_name="Difficulty of implementation"),
                ),
                (
                    "conditions_for_implementation",
                    models.TextField(verbose_name="Conditions for implementation"),
                ),
                ("quantification", models.TextField(verbose_name="Quantification")),
                (
                    "time_horizon",
                    models.CharField(max_length=100, verbose_name="Time horizon"),
                ),
                ("related", models.TextField(verbose_name="Related")),
                ("conflict", models.TextField(verbose_name="Conflict")),
                ("other_conflict", models.TextField(verbose_name="Other conflict")),
                (
                    "advantages",
                    models.ManyToManyField(
                        to="catalog.advantage", verbose_name="Advantages"
                    ),
                ),
                (
                    "disadvantages",
                    models.ManyToManyField(
                        to="catalog.disadvantage", verbose_name="Disadvantages"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.group",
                        verbose_name="Group",
                    ),
                ),
                ("tag", models.ManyToManyField(to="catalog.tag", verbose_name="Tags")),
            ],
            options={
                "verbose_name": "Subgroup",
                "verbose_name_plural": "Subgroups",
            },
        ),
        migrations.CreateModel(
            name="TagDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_detail", models.TextField(verbose_name="Tag detail")),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.tag",
                        verbose_name="Tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag detail",
                "verbose_name_plural": "Tag details",
            },
        ),
    ]
