# Generated by Django 5.2.3 on 2025-06-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name_cs",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Group Name (Czech)"
                    ),
                ),
                (
                    "group_name_eng",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Group Name (English)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group_name_cs", "group_name_eng"),
                        name="unique_group_names",
                    )
                ],
            },
        ),
    ]
