# Generated by Django 5.2.3 on 2025-06-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="group_name_cs",
            field=models.CharField(
                max_length=60, unique=True, verbose_name="Group Name (Czech)"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="group_name_eng",
            field=models.CharField(
                max_length=60, unique=True, verbose_name="Group Name (English)"
            ),
        ),
    ]
