# Generated by Django 5.2 on 2025-05-06 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advantage",
            options={"verbose_name": "Výhoda", "verbose_name_plural": "Výhody"},
        ),
        migrations.AlterModelOptions(
            name="choice",
            options={
                "ordering": ["choice_name", "order"],
                "verbose_name": "Volba",
                "verbose_name_plural": "Volby",
            },
        ),
        migrations.AlterModelOptions(
            name="choicename",
            options={
                "verbose_name": "Název volby",
                "verbose_name_plural": "Názvy voleb",
            },
        ),
        migrations.AlterModelOptions(
            name="disadvantage",
            options={"verbose_name": "Nevýhoda", "verbose_name_plural": "Nevýhody"},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Skupina", "verbose_name_plural": "Skupiny"},
        ),
        migrations.AlterModelOptions(
            name="localization",
            options={"verbose_name": "Lokalizace", "verbose_name_plural": "Lokalizace"},
        ),
        migrations.AlterModelOptions(
            name="subgroup",
            options={"verbose_name": "Podskupina", "verbose_name_plural": "Podskupiny"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "verbose_name": "Kategorie dopadu změny klimatu",
                "verbose_name_plural": "Kategorie dopadu změny klimatu",
            },
        ),
        migrations.AlterModelOptions(
            name="tagdetail",
            options={
                "verbose_name": "Kategorie dopadu změny klimatu (Specifický dopad)",
                "verbose_name_plural": "Kategorie dopadu změny klimatu (Specifické dopady)",
            },
        ),
        migrations.AddField(
            model_name="subgroup",
            name="comment",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Komentář"
            ),
        ),
        migrations.AddField(
            model_name="subgroup",
            name="other_tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="other_tags",
                to="catalog.tagdetail",
                verbose_name="Vedlejší kategorie dopadu změny klimatu",
            ),
        ),
        migrations.AddField(
            model_name="subgroup",
            name="price",
            field=models.PositiveIntegerField(default=0, verbose_name="Hodnota"),
        ),
        migrations.AddField(
            model_name="subgroup",
            name="sdg",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"choice_name_id": 10},
                related_name="sdgs",
                to="catalog.choice",
                verbose_name="Cíle udržitelného rozvoje (SDG)",
            ),
        ),
        migrations.AddField(
            model_name="subgroup",
            name="tag_desc",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Kategorie dopadu změny klimatu - poznánka",
            ),
        ),
        migrations.AddField(
            model_name="subgroup",
            name="unit",
            field=models.ForeignKey(
                limit_choices_to={"choice_name_id": 11},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="catalog.choice",
                verbose_name="Jednotka",
            ),
        ),
        migrations.AlterField(
            model_name="advantage",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Výhoda"),
        ),
        migrations.AlterField(
            model_name="choice",
            name="choice",
            field=models.CharField(max_length=255, verbose_name="Volba"),
        ),
        migrations.AlterField(
            model_name="choice",
            name="choice_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.choicename",
                verbose_name="Název volby",
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Popis"),
        ),
        migrations.AlterField(
            model_name="choice",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Pořadí"),
        ),
        migrations.AlterField(
            model_name="choicename",
            name="choice_name",
            field=models.CharField(max_length=255, verbose_name="Název volby"),
        ),
        migrations.AlterField(
            model_name="disadvantage",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Nevýhoda"),
        ),
        migrations.AlterField(
            model_name="group",
            name="group_name",
            field=models.CharField(max_length=30, verbose_name="Pojmenování skupiny"),
        ),
        migrations.AlterField(
            model_name="group",
            name="localization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.localization",
                verbose_name="Lokalizace",
            ),
        ),
        migrations.AlterField(
            model_name="localization",
            name="localization_name",
            field=models.CharField(
                max_length=30, verbose_name="Pojmenování lokalizace"
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="abstract",
            field=models.CharField(max_length=255, verbose_name="Shrnutí opatření"),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="advantages",
            field=models.ManyToManyField(to="catalog.advantage", verbose_name="Výhody"),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="code",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Kód opatření"
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="conditions_for_implementation",
            field=models.TextField(null=True, verbose_name="Podmínky implementace"),
        ),
        migrations.AlterUniqueTogether(
            name="subgroup",
            unique_together={("group", "subgroup_name")},
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="description",
            field=models.TextField(verbose_name="Podrobný popis opatření"),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="difficulty_of_implementation",
            field=models.ForeignKey(
                limit_choices_to={"choice_name_id": 4},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="difficulty_of_implementations",
                to="catalog.choice",
                verbose_name="Náročnost realizace",
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="disadvantages",
            field=models.ManyToManyField(
                to="catalog.disadvantage", verbose_name="Nevýhody"
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="env",
            field=models.ForeignKey(
                limit_choices_to={"choice_name_id": 1},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="envs",
                to="catalog.choice",
                verbose_name="Složka ŽP",
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="env_desc",
            field=models.TextField(
                blank=True, null=True, verbose_name="Složka ŽP (přesah) - poznánka"
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.group",
                verbose_name="Skupina",
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="mix_localization",
            field=models.BooleanField(
                default=False, verbose_name="Přesah lokalizace extravilán - intravilán"
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="other_conflict",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Jiné střety"
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="potential",
            field=models.ForeignKey(
                limit_choices_to={"choice_name_id": 2},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="potentials",
                to="catalog.choice",
                verbose_name="Potenciál aplikace",
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="quantification",
            field=models.ForeignKey(
                limit_choices_to={"choice_name_id": 5},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quantifications",
                to="catalog.choice",
                verbose_name="Kvantifikace dopadu",
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="size",
            field=models.ForeignKey(
                limit_choices_to={"choice_name_id": 3},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizes",
                to="catalog.choice",
                verbose_name="Rozsah / velikost",
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="subgroup_name",
            field=models.CharField(
                max_length=100, verbose_name="Pojmenování podskupiny"
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="time_horizon",
            field=models.ForeignKey(
                limit_choices_to={"choice_name_id": 6},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_horizons",
                to="catalog.choice",
                verbose_name="Časový horizont dopadu",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_name",
            field=models.CharField(max_length=50, verbose_name="Kategorie"),
        ),
        migrations.AlterField(
            model_name="tagdetail",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.tag",
                verbose_name="Kategorie dopadu změny klimatu",
            ),
        ),
        migrations.AlterField(
            model_name="tagdetail",
            name="tag_detail",
            field=models.CharField(max_length=100, verbose_name="Specifický dopad"),
        ),
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "example_name",
                    models.CharField(max_length=100, verbose_name="Název"),
                ),
                ("description", models.TextField(verbose_name="Popis")),
                ("web", models.URLField(verbose_name="Odkaz na www")),
                (
                    "location",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "v ČR"),
                            (2, "v zahraničí"),
                            (3, "v rámci DIVILAND"),
                        ],
                        verbose_name="Lokace",
                    ),
                ),
                (
                    "subgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.subgroup",
                        verbose_name="Podskupina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Realizováno (příklad)",
                "verbose_name_plural": "Realizováno (příklady)",
            },
        ),
        migrations.RemoveField(
            model_name="subgroup",
            name="conflict",
        ),
        migrations.RemoveField(
            model_name="subgroup",
            name="env_secondary",
        ),
        migrations.RemoveField(
            model_name="subgroup",
            name="related",
        ),
        migrations.RemoveField(
            model_name="subgroup",
            name="tag",
        ),
        migrations.AddField(
            model_name="subgroup",
            name="conflict",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"choice_name_id": 7},
                related_name="conflicts",
                to="catalog.choice",
                verbose_name="Střet",
            ),
        ),
        migrations.AddField(
            model_name="subgroup",
            name="env_secondary",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"choice_name_id": 1},
                related_name="envs_sec",
                to="catalog.choice",
                verbose_name="Složka ŽP (přesah)",
            ),
        ),
        migrations.AddField(
            model_name="subgroup",
            name="related",
            field=models.ManyToManyField(
                blank=True, to="catalog.subgroup", verbose_name="Návaznost"
            ),
        ),
        migrations.AddField(
            model_name="subgroup",
            name="tag",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="catalog.tagdetail",
                verbose_name="Kategorie dopadu změny klimatu",
            ),
        ),
    ]
