# Generated by Django 5.2.3 on 2025-06-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_group_group_name_cs_alter_group_group_name_eng"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advantage_description_cs",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Advantage (Czech)"
                    ),
                ),
                (
                    "advantage_description_en",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Advantage (English)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Advantage",
                "verbose_name_plural": "Advantages",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("advantage_description_cs", "advantage_description_en"),
                        name="unique_advantage_descriptions",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Disadvantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disadvantage_description_cs",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Disadvantage (Czech)"
                    ),
                ),
                (
                    "disadvantage_description_en",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Disadvantage (English)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disadvantage",
                "verbose_name_plural": "Disadvantages",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "disadvantage_description_cs",
                            "disadvantage_description_en",
                        ),
                        name="unique_disadvantage_descriptions",
                    )
                ],
            },
        ),
    ]
