# Generated by Django 5.2.3 on 2025-06-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_advantage_disadvantage"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptionName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_name_cs",
                    models.CharField(
                        max_length=255, verbose_name="Option name (Czech)"
                    ),
                ),
                (
                    "option_name_en",
                    models.CharField(
                        max_length=255, verbose_name="Option name (English)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Option name",
                "verbose_name_plural": "Option names",
            },
        ),
        migrations.RemoveConstraint(
            model_name="group",
            name="unique_group_names",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="group_name_eng",
            new_name="group_name_en",
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("group_name_cs", "group_name_en"), name="unique_group_names"
            ),
        ),
        migrations.AddConstraint(
            model_name="optionname",
            constraint=models.UniqueConstraint(
                fields=("option_name_cs", "option_name_en"), name="unique_option_names"
            ),
        ),
    ]
