# Generated by Django 5.2.3 on 2025-06-24 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_optionname_remove_group_unique_group_names_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_cs",
                    models.CharField(max_length=255, verbose_name="Option (Czech)"),
                ),
                (
                    "option_en",
                    models.CharField(max_length=255, verbose_name="Option (English)"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Order"),
                ),
                (
                    "description_cs",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description (Czech)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description (English)"
                    ),
                ),
                (
                    "option_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.optionname",
                        verbose_name="Option Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Option",
                "verbose_name_plural": "Options",
                "ordering": ["option_name", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("option_cs", "option_en"), name="unique_options"
                    ),
                    models.UniqueConstraint(
                        fields=("description_cs", "description_en"),
                        name="unique_descriptions",
                    ),
                ],
            },
        ),
    ]
