# Generated by Django 5.2.3 on 2025-06-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_option"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="option",
            name="unique_options",
        ),
        migrations.RemoveConstraint(
            model_name="option",
            name="unique_descriptions",
        ),
        migrations.AddConstraint(
            model_name="option",
            constraint=models.UniqueConstraint(
                fields=("option_name", "option_cs", "option_en"), name="unique_options"
            ),
        ),
        migrations.AddConstraint(
            model_name="option",
            constraint=models.UniqueConstraint(
                fields=("option_name", "description_cs", "description_en"),
                name="unique_descriptions",
            ),
        ),
    ]
