# Generated by Django 5.2.3 on 2025-06-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_remove_option_unique_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpactCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "impact_category_name_cs",
                    models.CharField(
                        max_length=100, verbose_name="Impact Category (Czech)"
                    ),
                ),
                (
                    "impact_category_name_en",
                    models.CharField(
                        max_length=100, verbose_name="Impact Category (English)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Impact category",
                "verbose_name_plural": "Impact categories",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("impact_category_name_cs", "impact_category_name_en"),
                        name="impact_category_name_unique",
                    )
                ],
            },
        ),
    ]
