# Generated by Django 5.2.3 on 2025-06-24 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_impactcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpactDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "impact_detail_cs",
                    models.CharField(
                        max_length=100, verbose_name="Impact detail (Czech)"
                    ),
                ),
                (
                    "impact_detail_en",
                    models.CharField(
                        max_length=100, verbose_name="Impact detail (English)"
                    ),
                ),
                (
                    "impact_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.impactcategory",
                        verbose_name="Impact Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impact detail",
                "verbose_name_plural": "Impact details",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "impact_category",
                            "impact_detail_cs",
                            "impact_detail_en",
                        ),
                        name="impact_detail_unique",
                    )
                ],
            },
        ),
    ]
