# Generated by Django 5.2.3 on 2025-06-24 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_measure"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measure",
            options={"verbose_name": "Measure", "verbose_name_plural": "Measures"},
        ),
        migrations.AlterField(
            model_name="measure",
            name="advantages",
            field=models.ManyToManyField(
                blank=True, to="catalog.advantage", verbose_name="Advantages"
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="conditions_for_implementation_cs",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Conditions of implementation (Czech)",
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="conditions_for_implementation_en",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Conditions of implementation (English)",
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="conflict",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"option_name__id": 7},
                related_name="conflicts",
                to="catalog.option",
                verbose_name="Conflicts",
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="difficulty_of_implementation",
            field=models.ForeignKey(
                limit_choices_to={"option_name__id": 4},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="difficulty_of_implementations",
                to="catalog.option",
                verbose_name="Implementation complexity",
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="disadvantages",
            field=models.ManyToManyField(
                blank=True, to="catalog.disadvantage", verbose_name="Disadvantages"
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="env",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"option_name__id": 1},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="envs",
                to="catalog.option",
                verbose_name="Environmental compartment",
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="env_secondary",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"option_name__id": 1},
                related_name="envs_sec",
                to="catalog.option",
                verbose_name="Environmental compartment (overlap)",
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="impact_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="impacts",
                to="catalog.impactdetail",
                verbose_name="Impact categories of climate change",
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="potential",
            field=models.ForeignKey(
                limit_choices_to={"option_name__id": 2},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="potentials",
                to="catalog.option",
                verbose_name="Application potential",
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="quantification",
            field=models.ForeignKey(
                limit_choices_to={"option_name__id": 5},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rel_quantification",
                to="catalog.option",
                verbose_name="Impact quantification",
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="sdg",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"option_name__id": 10},
                related_name="rel_sdg",
                to="catalog.option",
                verbose_name="Sustainable Development Goals (SDG)",
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="size",
            field=models.ForeignKey(
                limit_choices_to={"option_name__id": 3},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizes",
                to="catalog.option",
                verbose_name="Scale / extent",
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="time_horizon",
            field=models.ForeignKey(
                limit_choices_to={"option_name__id": 6},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_horizons",
                to="catalog.option",
                verbose_name="Impact time horizon",
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="unit",
            field=models.ForeignKey(
                limit_choices_to={"option_name__id": 11},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="catalog.option",
                verbose_name="Unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="measure",
            constraint=models.UniqueConstraint(
                fields=("measure_name_cs", "measure_name_en", "code"),
                name="unique_measure_names_and_code",
            ),
        ),
    ]
