# Generated by Django 5.2.3 on 2025-06-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_remove_measure_unique_measure_names_and_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="measure_name_cs",
            field=models.CharField(max_length=100, verbose_name="Measure name (Czech)"),
        ),
        migrations.AlterField(
            model_name="measure",
            name="measure_name_en",
            field=models.CharField(
                max_length=100, verbose_name="Measure name (English)"
            ),
        ),
    ]
