# Generated by Django 5.2.3 on 2025-06-25 08:28

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_example"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "expertise",
                    models.CharField(max_length=255, verbose_name="Expertise"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Phone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Person",
                "verbose_name_plural": "Contact Persons",
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(max_length=255, verbose_name="Reference"),
                ),
                ("url", models.URLField(verbose_name="URL")),
            ],
        ),
        migrations.AddField(
            model_name="measure",
            name="original_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="measure_images/originals/",
                verbose_name="Original Image",
            ),
        ),
        migrations.AddField(
            model_name="measure",
            name="title_image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                null=True,
                upload_to="measure_images/processed/",
                verbose_name="Title Image",
            ),
        ),
        migrations.AddField(
            model_name="measure",
            name="contact_persons",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_persons",
                to="catalog.contactperson",
                verbose_name="Contact person",
            ),
        ),
        migrations.CreateModel(
            name="MeasureImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(
                        upload_to="photos/%Y/%m/%d/", verbose_name="Original Image"
                    ),
                ),
                (
                    "caption_cs",
                    models.CharField(max_length=255, verbose_name="Caption (Czech)"),
                ),
                (
                    "caption_en",
                    models.CharField(max_length=255, verbose_name="Caption (English)"),
                ),
                ("author", models.CharField(max_length=255, verbose_name="Author")),
                ("license", models.CharField(max_length=255, verbose_name="License")),
                (
                    "license_url",
                    models.URLField(blank=True, null=True, verbose_name="License URL"),
                ),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="catalog.measure",
                        verbose_name="Related Measure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Measure Image",
                "verbose_name_plural": "Measure Images",
            },
        ),
        migrations.AddField(
            model_name="measure",
            name="references",
            field=models.ManyToManyField(
                blank=True,
                related_name="measure_references",
                to="catalog.reference",
                verbose_name="References",
            ),
        ),
    ]
