# Generated by Django 5.2.3 on 2025-06-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_contactperson_reference_measure_original_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="history_cs",
            field=models.TextField(
                blank=True, null=True, verbose_name="History (Czech)"
            ),
        ),
        migrations.AddField(
            model_name="measure",
            name="history_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="History (English)"
            ),
        ),
    ]
