# Generated by Django 5.2.3 on 2025-06-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_measure_history_cs_measure_history_en"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measure",
            name="price_czk",
        ),
        migrations.RemoveField(
            model_name="measure",
            name="price_eu",
        ),
    ]
