# Generated by Django 5.2.3 on 2025-06-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_remove_measure_price_czk_remove_measure_price_eu"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="price_czk_max",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Price (CZK) - To"
            ),
        ),
        migrations.AddField(
            model_name="measure",
            name="price_czk_min",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Price (CZK) - From"
            ),
        ),
        migrations.AddField(
            model_name="measure",
            name="price_eu_max",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Price (Euro) - To"
            ),
        ),
        migrations.AddField(
            model_name="measure",
            name="price_eu_min",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Price (Euro) - From"
            ),
        ),
    ]
