# Generated by Django 5.2.3 on 2025-06-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_measure_price_czk_max_measure_price_czk_min_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measure",
            name="original_image",
        ),
        migrations.AlterField(
            model_name="measure",
            name="title_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="measure_images/originals/",
                verbose_name="Original Image",
            ),
        ),
    ]
