# Generated by Django 5.2.3 on 2025-07-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_remove_measure_original_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dzes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="Code")),
                (
                    "name_cs",
                    models.CharField(max_length=100, verbose_name="Name (Czech)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="Name (English)"),
                ),
                (
                    "url_cs",
                    models.URLField(blank=True, null=True, verbose_name="URL (Czech)"),
                ),
                (
                    "url_en",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL (English)"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="measure",
            name="dzes",
            field=models.ManyToManyField(to="catalog.dzes", verbose_name="Dzes"),
        ),
    ]
