# Generated by Django 5.2.3 on 2025-07-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_dzes_measure_dzes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dzes",
            name="code",
            field=models.CharField(max_length=10, verbose_name="Code DZES"),
        ),
    ]
