# Generated by Django 5.2.3 on 2025-07-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_alter_dzes_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dzes",
            options={"verbose_name": "Dzes", "verbose_name_plural": "Dzes"},
        ),
    ]
