# Generated by Django 5.2.3 on 2025-07-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_ppt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ppt",
            options={"verbose_name": "PPT", "verbose_name_plural": "PPT"},
        ),
    ]
