# Generated by Django 5.2.3 on 2025-07-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0023_alter_ppt_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="ppt",
            field=models.ManyToManyField(to="catalog.ppt", verbose_name="PPT"),
        ),
    ]
