# Generated by Django 5.2.3 on 2025-07-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0025_pph_remove_measure_ppt_measure_pph_delete_ppt"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="invasion",
            field=models.TextField(
                blank=True, null=True, verbose_name="invasive species issue"
            ),
        ),
    ]
