# Generated by Django 5.2.3 on 2025-09-10 13:25

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_measure_invasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='conditions_for_implementation_cs',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Conditions of implementation (Czech)'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='conditions_for_implementation_en',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Conditions of implementation (English)'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='history_cs',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='History (Czech)'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='history_en',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='History (English)'),
        ),
    ]
