# Generated by Django 5.2.3 on 2025-09-10 20:01

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_alter_measure_conditions_for_implementation_cs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='description_cs',
            field=markdownx.models.MarkdownxField(verbose_name='Description (Czech)'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='description_en',
            field=markdownx.models.MarkdownxField(verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='invasion',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='invasive species issue'),
        ),
    ]
