# Generated by Django 5.2.3 on 2025-09-10 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_alter_measure_description_cs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measure',
            old_name='invasion',
            new_name='invasion_cs',
        ),
    ]
