# Generated by Django 5.2.3 on 2025-09-10 20:13

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_rename_invasion_measure_invasion_cs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='invasion_cs',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='invasive species issue (cs)'),
        ),
    ]
