# Generated by Django 5.2.3 on 2025-09-10 20:14

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_alter_measure_invasion_cs'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='invasion_em',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='invasive species issue (en)'),
        ),
    ]
