# Generated by Django 5.2.3 on 2025-09-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_measure_invasion_em'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measure',
            old_name='invasion_em',
            new_name='invasion_en',
        ),
    ]
