# Generated by Django 5.2.3 on 2025-09-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_rename_invasion_em_measure_invasion_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='pre_project_preparation',
            field=models.ManyToManyField(blank=True, limit_choices_to={'option_name__id': 13}, related_name='rel_ppp', to='catalog.option', verbose_name='Pre-project preparation'),
        ),
    ]
