# Generated by Django 5.2.3 on 2025-09-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0033_measure_pre_project_preparation"),
    ]

    operations = [
        migrations.CreateModel(
            name="NatureRestorationLaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="Code DZES")),
                (
                    "name_cs",
                    models.CharField(max_length=100, verbose_name="Name (Czech)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="Name (English)"),
                ),
                (
                    "url_cs",
                    models.URLField(blank=True, null=True, verbose_name="URL (Czech)"),
                ),
                (
                    "url_en",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL (English)"
                    ),
                ),
            ],
            options={
                "verbose_name": "NatureRestorationLaw",
                "verbose_name_plural": "NatureRestorationLaw",
            },
        ),
    ]
