# Generated by Django 5.2.3 on 2025-09-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0034_naturerestorationlaw"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="nature_restoration_law",
            field=models.ManyToManyField(
                to="catalog.naturerestorationlaw", verbose_name="Nature restoration law"
            ),
        ),
    ]
