# Generated by Django 5.2.3 on 2025-09-12 20:21

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0035_measure_nature_restoration_law"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_cs", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("content_cs", markdownx.models.MarkdownxField()),
                ("content_en", markdownx.models.MarkdownxField()),
                (
                    "is_home",
                    models.BooleanField(
                        default=False, help_text="Tahle stránka je titulka"
                    ),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_home", True)),
                        fields=("is_home",),
                        name="only_one_homepage",
                    )
                ],
            },
        ),
    ]
