# Generated by Django 5.2.3 on 2025-09-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0036_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reference",
            options={"verbose_name": "Reference", "verbose_name_plural": "References"},
        ),
    ]
