# Generated by Django 5.2.3 on 2025-09-15 08:38

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0037_alter_reference_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measure",
            old_name="other_conflict",
            new_name="other_conflict_cs",
        ),
        migrations.AlterField(
            model_name="measure",
            name="invasion_cs",
            field=markdownx.models.MarkdownxField(
                blank=True, null=True, verbose_name="Invasive species issue (cs)"
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="invasion_en",
            field=markdownx.models.MarkdownxField(
                blank=True, null=True, verbose_name="Invasive species issue (en)"
            ),
        ),
    ]
