# Generated by Django 5.2.3 on 2025-09-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0038_rename_other_conflict_measure_other_conflict_cs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="other_conflict_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Other conflicts (English)",
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="other_conflict_cs",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Other conflicts (Czech)",
            ),
        ),
    ]
