# Generated by Django 5.2.3 on 2025-09-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0039_measure_other_conflict_en_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="naturerestorationlaw",
            options={
                "verbose_name": "Nature Restoration Law",
                "verbose_name_plural": "Nature Restoration Laws",
            },
        ),
        migrations.AddField(
            model_name="measure",
            name="potential_scale",
            field=models.CharField(
                choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                default="M",
                max_length=1,
                verbose_name="Application potential scale",
            ),
        ),
    ]
