# Generated by Django 5.2.3 on 2025-09-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0040_alter_naturerestorationlaw_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="size_scale",
            field=models.CharField(
                choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                default="M",
                max_length=1,
                verbose_name="Scale / extent - scale",
            ),
        ),
    ]
