# Generated by Django 5.2.3 on 2025-09-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0041_measure_size_scale"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="difficulty_of_implementation_scale",
            field=models.CharField(
                choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                default="M",
                max_length=1,
                verbose_name="Implementation complexity - scale",
            ),
        ),
        migrations.AddField(
            model_name="measure",
            name="quantification_scale",
            field=models.CharField(
                choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                default="M",
                max_length=1,
                verbose_name="Impact quantification - scale",
            ),
        ),
        migrations.AddField(
            model_name="measure",
            name="time_horizon_scale",
            field=models.CharField(
                choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                default="M",
                max_length=1,
                verbose_name="Impact time horizon - scale",
            ),
        ),
    ]
