# Generated by Django 5.2.3 on 2025-09-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0042_measure_difficulty_of_implementation_scale_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measure",
            old_name="unit",
            new_name="unit_czk",
        ),
        migrations.AlterField(
            model_name="naturerestorationlaw",
            name="code",
            field=models.CharField(max_length=10, verbose_name="Code NPOP"),
        ),
    ]
