# Generated by Django 5.2.3 on 2025-09-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0043_rename_unit_measure_unit_czk_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measure",
            old_name="contact_persons",
            new_name="contact_person",
        ),
    ]
