# Generated by Django 5.2.3 on 2025-09-15 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0044_rename_contact_persons_measure_contact_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="example",
            name="measure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examples",
                to="catalog.measure",
                verbose_name="Measure",
            ),
        ),
    ]
