# Generated by Django 5.2.3 on 2025-09-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0045_alter_example_measure"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measure",
            old_name="unit_czk",
            new_name="unit",
        ),
    ]
