# Generated by Django 5.2.3 on 2025-11-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0046_rename_unit_czk_measure_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="measures",
                to="catalog.group",
                verbose_name="Group",
            ),
        ),
    ]
