# Generated by Django 5.2.3 on 2025-11-18 14:18

from django.db import migrations

def copy_group_to_groups(apps, schema_editor):
    Measure = apps.get_model("catalog", "Measure")
    for measure in Measure.objects.all():
        if measure.group_id:
            measure.groups.add(measure.group_id)



class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0047_measure_groups"),
    ]

    operations = [
        migrations.RunPython(copy_group_to_groups, migrations.RunPython.noop),
    ]

