# Generated by Django 5.2.3 on 2025-11-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0048_copy_group_to_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measure",
            name="group",
        ),
    ]
