# Generated by Django 5.2.3 on 2025-12-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0050_remove_measure_unique_measure_names_and_code_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="measure",
            name="unique_measure_names_and_code",
        ),
        migrations.AddField(
            model_name="contactperson",
            name="title_after",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Title After Name"
            ),
        ),
        migrations.AddField(
            model_name="contactperson",
            name="title_before",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Title Before Name"
            ),
        ),
    ]
