# Generated by Django 5.2.3 on 2025-12-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0051_remove_measure_unique_measure_names_and_code_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="measure",
            constraint=models.UniqueConstraint(
                fields=("measure_name_cs", "measure_name_en", "code"),
                name="unique_measure_names_and_code",
            ),
        ),
    ]
