# Generated by Django 5.2.3 on 2026-01-03 14:25

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0052_measure_unique_measure_names_and_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoxName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("box_number", models.IntegerField(verbose_name="Box number")),
                (
                    "name_cs",
                    models.CharField(max_length=100, verbose_name="Name (Czech)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="Name (English)"),
                ),
                (
                    "description_cs",
                    models.CharField(
                        max_length=255, verbose_name="Description (Czech)"
                    ),
                ),
                (
                    "description_en",
                    models.CharField(
                        max_length=255, verbose_name="Description (English)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Box name",
                "verbose_name_plural": "Box names",
            },
            bases=(models.Model, catalog.models.TranslateMixin),
        ),
    ]
