# Generated by Django 5.2.9 on 2026-01-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0053_boxname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactperson",
            name="expertise",
        ),
        migrations.AddField(
            model_name="contactperson",
            name="expertise_cs",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Expertise (Česky)"
            ),
            preserve_default=False,
        ),
    ]
