# Generated by Django 5.2.9 on 2026-01-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0054_remove_contactperson_expertise_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactperson",
            name="expertise_cs",
            field=models.CharField(max_length=255, verbose_name="Expertise (English)"),
        ),
    ]
