# Generated by Django 5.2.9 on 2026-01-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0055_alter_contactperson_expertise_cs"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactperson",
            name="expertise_en",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Expertise (English)"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="expertise_cs",
            field=models.CharField(max_length=255, verbose_name="Expertise (Czech)"),
        ),
    ]
